In [2]:
! pip install numpy

You should consider upgrading via the 'pip install --upgrade pip' command.


In [3]:
import numpy as np

In [5]:
l1 = [1,2,3,4]
l2 = [5,6,7,8]

In [6]:
l1+l2

[1, 2, 3, 4, 5, 6, 7, 8]

In [8]:
arr1 = np.array(l1)
arr2 = np.array(l2)

In [9]:
arr1

array([1, 2, 3, 4])

In [10]:
arr2

array([5, 6, 7, 8])

In [11]:
arr1 + arr2

array([ 6,  8, 10, 12])

In [12]:
arr2- arr1

array([4, 4, 4, 4])

In [13]:
type(arr1)

numpy.ndarray

In [14]:
arr1.shape

(4,)

In [22]:
a = np.array([[1],
              [2],
              [3],
              [4]])

In [23]:
a.shape

(4, 1)

In [25]:
arr1 = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

In [26]:
arr1.shape

(3, 3)

In [27]:
arr2 = arr1

In [29]:
arr2.shape

(3, 3)

In [30]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
arr1 * arr2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [36]:
np.dot(arr1, arr2)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [37]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [39]:
# np.transpose(arr1)
arr1.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [40]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
np.sum(arr1)

45

In [42]:
np.max(arr1)

9

In [45]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [52]:
np.reshape(arr1, (1,-1))

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

## random

In [70]:
A = np.random.randint(10,100, size=(5,5))

In [71]:
A

array([[18, 78, 45, 29, 37],
       [36, 31, 99, 41, 61],
       [31, 25, 71, 18, 67],
       [60, 77, 78, 48, 64],
       [44, 92, 64, 74, 80]])

In [74]:
A[-1,-1]

80

In [75]:
# Array Slicing
# A[ rows  , cols ]
A[ 2:5  , 2:4   ]

array([[71, 18],
       [78, 48],
       [64, 74]])

In [76]:
A[  2 ,  :   ]

array([31, 25, 71, 18, 67])

In [79]:
A[ : ,  1:3 ]

array([[78, 45],
       [31, 99],
       [25, 71],
       [77, 78],
       [92, 64]])

In [81]:
A.shape

(5, 5)

In [85]:
a.shape

(4, 1)

In [92]:
arr1**2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [96]:
a = np.array([[1,2,3]])

In [97]:
a

array([[1, 2, 3]])

In [98]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [99]:
a + arr1

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [100]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [102]:
arr1 + A

ValueError: operands could not be broadcast together with shapes (3,3) (5,5) 

In [104]:
def distance(pA, pB):
    return np.sum((pB-pA)**2)**0.5

In [109]:
pB = np.array([5,5,6,8,3,9,0,2])
pA = np.array([0,0,7,9,2,7,4,1])

In [110]:
distance(pA, pB)

8.602325267042627

In [112]:
np.sin(90)

0.8939966636005579

In [114]:
arr1.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])